"""Plan-only MVPA configuration and discovery contracts."""

from __future__ import annotations

from .config import (
    ConditionDefinition,
    ConditionPairConfig,
    DistanceConfig,
    EventThresholdConfig,
    ExclusionRule,
    MeanCenteringConfig,
    MissingInputPolicy,
    MvpaEntities,
    MvpaSetConfig,
    NoiseNormalizationConfig,
    OutputConfig,
    OutputRootConfig,
    PatternSourceConfig,
    ProvenanceConfig,
    PublicationConfig,
    RoiSourceConfig,
    SubjectSessionRunSelector,
    ThresholdSweepConfig,
    parse_mvpa_set_document,
    validate_mvpa_set_document,
)
from .plan import (
    ConditionPlanRow,
    DistancePlanRow,
    ExclusionPlanRow,
    MissingInputPlanRow,
    MvpaDiscoveryPlan,
    OutputPreviewRow,
    PatternSourcePlanRow,
    RoiSourcePlanRow,
    plan_mvpa_discovery,
)
from .fsl_feat import (
    FslFeatConditionPePlanRow,
    FslFeatInputCheckRow,
    FslFeatPatternSourcePlan,
    FslFeatPatternSourcePlanRow,
    plan_fsl_feat_pattern_source,
)
from .roi_sources import (
    MvpaRoiInputCheckRow,
    MvpaRoiProvenancePlanRow,
    MvpaRoiSourcePlan,
    MvpaRoiSourcePlanRow,
    plan_mvpa_roi_sources,
)
from .workflow import (
    ConditionPair,
    ConditionPairPlanRow,
    LosoWorkflowSettings,
    MvpaFeatSourceConfig,
    MvpaFeatSourcePlanRow,
    MvpaWorkflowExtensionConfig,
    MvpaWorkflowExtensionPlan,
    PeMappingAlias,
    PeMappingAliasPlanRow,
    RoiCollectionConfig,
    RoiCollectionPlanRow,
    RunExclusion,
    RunExclusionPlanRow,
    ThresholdSweep,
    ThresholdSweepPlanRow,
    TransformPlanRow,
    TransformSettings,
    parse_mvpa_workflow_extension_document,
    plan_mvpa_workflow_extension,
    validate_mvpa_workflow_extension_document,
)
from .scaffold import (
    COMPARISONS_COLUMNS as MVPA_SCAFFOLD_COMPARISONS_COLUMNS,
    CONDITIONS_COLUMNS as MVPA_SCAFFOLD_CONDITIONS_COLUMNS,
    ROIS_COLUMNS as MVPA_SCAFFOLD_ROIS_COLUMNS,
    SUPPORTED_COMPONENTS as MVPA_SCAFFOLD_SUPPORTED_COMPONENTS,
    SUPPORTED_COMPARISON_MODES as MVPA_SCAFFOLD_SUPPORTED_COMPARISON_MODES,
    SUPPORTED_TEMPLATES as MVPA_SCAFFOLD_SUPPORTED_TEMPLATES,
    build_mvpa_config_scaffold,
    normalize_components as normalize_mvpa_scaffold_components,
)


__all__ = [
    "ConditionDefinition",
    "ConditionPairConfig",
    "ConditionPair",
    "ConditionPairPlanRow",
    "ConditionPlanRow",
    "DistanceConfig",
    "DistancePlanRow",
    "EventThresholdConfig",
    "ExclusionRule",
    "ExclusionPlanRow",
    "FslFeatConditionPePlanRow",
    "FslFeatInputCheckRow",
    "FslFeatPatternSourcePlan",
    "FslFeatPatternSourcePlanRow",
    "LosoWorkflowSettings",
    "MeanCenteringConfig",
    "MissingInputPlanRow",
    "MissingInputPolicy",
    "MVPA_SCAFFOLD_COMPARISONS_COLUMNS",
    "MVPA_SCAFFOLD_CONDITIONS_COLUMNS",
    "MVPA_SCAFFOLD_ROIS_COLUMNS",
    "MVPA_SCAFFOLD_SUPPORTED_COMPONENTS",
    "MVPA_SCAFFOLD_SUPPORTED_COMPARISON_MODES",
    "MVPA_SCAFFOLD_SUPPORTED_TEMPLATES",
    "MvpaFeatSourceConfig",
    "MvpaFeatSourcePlanRow",
    "MvpaDiscoveryPlan",
    "MvpaEntities",
    "MvpaRoiInputCheckRow",
    "MvpaRoiProvenancePlanRow",
    "MvpaRoiSourcePlan",
    "MvpaRoiSourcePlanRow",
    "MvpaSetConfig",
    "MvpaWorkflowExtensionConfig",
    "MvpaWorkflowExtensionPlan",
    "NoiseNormalizationConfig",
    "OutputConfig",
    "OutputPreviewRow",
    "OutputRootConfig",
    "PeMappingAlias",
    "PeMappingAliasPlanRow",
    "PatternSourceConfig",
    "PatternSourcePlanRow",
    "ProvenanceConfig",
    "PublicationConfig",
    "RoiSourceConfig",
    "RoiSourcePlanRow",
    "RoiCollectionConfig",
    "RoiCollectionPlanRow",
    "RunExclusion",
    "RunExclusionPlanRow",
    "SubjectSessionRunSelector",
    "ThresholdSweepConfig",
    "ThresholdSweep",
    "ThresholdSweepPlanRow",
    "TransformPlanRow",
    "TransformSettings",
    "parse_mvpa_set_document",
    "parse_mvpa_workflow_extension_document",
    "plan_fsl_feat_pattern_source",
    "plan_mvpa_discovery",
    "plan_mvpa_roi_sources",
    "plan_mvpa_workflow_extension",
    "validate_mvpa_set_document",
    "validate_mvpa_workflow_extension_document",
    "build_mvpa_config_scaffold",
    "normalize_mvpa_scaffold_components",
]
