from __future__ import annotations

from .adapters import DistanceEngine
from .contracts import (
    CrossValidationSpec,
    DistanceEstimate,
    DistanceRequest,
    METRIC_CORRELATION,
    METRIC_CROSSNOBIS,
    METRIC_EUCLIDEAN,
    NOISE_NORMALIZATION_DIAGONAL,
    NOISE_NORMALIZATION_IDENTITY,
    NoiseNormalization,
    PatternDataset,
    PatternObservation,
)
from .cv import condition_order, cv_units_by_condition, validate_cross_validation
from .native_reference import NativeReferenceDistanceEngine
from .manual_crossnobis import (
    DEFAULT_MANUAL_MIN_RETAINED_FEATURES,
    DEFAULT_MANUAL_WARN_DROPPED_FEATURE_FRACTION,
    ENGINE_MANUAL_DIAGONAL_CROSSNOBIS_V1,
    ManualCrossnobisResult,
    ManualCrossnobisRun,
    ManualCrossnobisRunPairDetail,
    ManualCrossnobisRunQc,
    NOISE_NONPOSITIVE_POLICY_DROP_FEATURES,
    NOISE_NONPOSITIVE_POLICY_DROP_PATTERN,
    NOISE_NONPOSITIVE_POLICY_FILTER_NONPOSITIVE_FEATURES,
    NOISE_NONPOSITIVE_POLICY_STRICT,
    SUPPORTED_NOISE_NONPOSITIVE_POLICIES,
    compute_manual_diagonal_crossnobis_v1,
)
from .prepared_distances import (
    PreparedMvpaDistanceProvenanceRow,
    PreparedMvpaDistanceQcRow,
    PreparedMvpaDistanceResult,
    PreparedMvpaDistanceRow,
    compute_mvpa_distances_from_prepared_groups,
)
from .prepared_summary import (
    DEFAULT_PREPARED_MVPA_DISTANCE_SUMMARY_GROUP_BY,
    PreparedMvpaDistanceSummaryProvenanceRow,
    PreparedMvpaDistanceSummaryQcRow,
    PreparedMvpaDistanceSummaryResult,
    prepared_mvpa_distance_summary_rows,
    summarize_prepared_mvpa_distances,
)
from .rdm import rdm_long_rows_from_estimates, rdm_wide_rows_from_estimates
from .row_preparation import (
    DEFAULT_MVPA_PATTERN_GROUP_BY,
    MvpaPatternRowPreparationProvenanceRow,
    MvpaPatternRowPreparationQcRow,
    MvpaPatternRowPreparationResult,
    PreparedMvpaPatternGroup,
    PreparedMvpaPatternRow,
    SUPPORTED_MVPA_ROW_PREPARATION_CV_UNITS,
    prepare_mvpa_pattern_row_groups,
)
from .runtime_outputs import (
    plan_prepared_mvpa_distance_outputs,
    plan_prepared_mvpa_pattern_outputs,
    plan_prepared_mvpa_summary_outputs,
    write_mvpa_runtime_json,
    write_mvpa_runtime_tsv,
    write_prepared_mvpa_distance_outputs,
    write_prepared_mvpa_pattern_outputs,
    write_prepared_mvpa_summary_outputs,
)
from .summary import distance_summary_rows_from_estimates, distance_summary_rows_from_long_rows
from .tables import (
    CONDITION_ID_COLUMN,
    CV_UNIT_COLUMN,
    DISTANCE_CONDITION_A_COLUMN,
    DISTANCE_CONDITION_B_COLUMN,
    DISTANCE_CV_UNIT_COUNT_COLUMN,
    DISTANCE_ENGINE_COLUMN,
    DISTANCE_METRIC_COLUMN,
    DISTANCE_NORMALIZATION_COLUMN,
    DISTANCE_VALUE_COLUMN,
    LONG_DISTANCE_COLUMNS,
    PATTERN_ID_COLUMN,
    RDM_INDEX_COLUMN,
    REQUIRED_PATTERN_COLUMNS,
    pattern_dataset_from_rows,
)
from .table_export import (
    AUDIT_COLUMNS as MVPA_TABLE_EXPORT_AUDIT_COLUMNS,
    TABLE_A_BASE_COLUMNS as MVPA_TABLE_EXPORT_TABLE_A_BASE_COLUMNS,
    plan_or_execute_mvpa_table_export,
    validate_mvpa_table_export_document,
)
from .figure_export import (
    SUPPORTED_FIGURE_KINDS as MVPA_FIGURE_EXPORT_SUPPORTED_KINDS,
    plan_or_execute_mvpa_figure_export,
    validate_mvpa_figure_export_document,
)
from .rdm_export import (
    SUPPORTED_RDM_KINDS as MVPA_RDM_EXPORT_SUPPORTED_KINDS,
    plan_or_execute_mvpa_rdm_export,
    validate_mvpa_rdm_export_document,
)
from .derivative_publish import (
    DEFAULT_TARGET as MVPA_DERIVATIVE_PUBLISH_DEFAULT_TARGET,
    plan_or_execute_mvpa_derivative_publish,
    validate_mvpa_derivative_publish_document,
)
from .publication_export import (
    plan_or_execute_mvpa_publication_export,
    validate_mvpa_publication_export_document,
)

__all__ = [
    "CONDITION_ID_COLUMN",
    "CV_UNIT_COLUMN",
    "CrossValidationSpec",
    "DEFAULT_MANUAL_MIN_RETAINED_FEATURES",
    "DEFAULT_MANUAL_WARN_DROPPED_FEATURE_FRACTION",
    "DEFAULT_MVPA_PATTERN_GROUP_BY",
    "DEFAULT_PREPARED_MVPA_DISTANCE_SUMMARY_GROUP_BY",
    "DISTANCE_CONDITION_A_COLUMN",
    "DISTANCE_CONDITION_B_COLUMN",
    "DISTANCE_CV_UNIT_COUNT_COLUMN",
    "DISTANCE_ENGINE_COLUMN",
    "DISTANCE_METRIC_COLUMN",
    "DISTANCE_NORMALIZATION_COLUMN",
    "DISTANCE_VALUE_COLUMN",
    "DistanceEngine",
    "DistanceEstimate",
    "DistanceRequest",
    "ENGINE_MANUAL_DIAGONAL_CROSSNOBIS_V1",
    "LONG_DISTANCE_COLUMNS",
    "METRIC_CORRELATION",
    "METRIC_CROSSNOBIS",
    "METRIC_EUCLIDEAN",
    "MVPA_TABLE_EXPORT_AUDIT_COLUMNS",
    "MVPA_TABLE_EXPORT_TABLE_A_BASE_COLUMNS",
    "MVPA_FIGURE_EXPORT_SUPPORTED_KINDS",
    "MVPA_RDM_EXPORT_SUPPORTED_KINDS",
    "MVPA_DERIVATIVE_PUBLISH_DEFAULT_TARGET",
    "MvpaPatternRowPreparationProvenanceRow",
    "MvpaPatternRowPreparationQcRow",
    "MvpaPatternRowPreparationResult",
    "ManualCrossnobisResult",
    "ManualCrossnobisRun",
    "ManualCrossnobisRunPairDetail",
    "ManualCrossnobisRunQc",
    "NOISE_NORMALIZATION_DIAGONAL",
    "NOISE_NORMALIZATION_IDENTITY",
    "NOISE_NONPOSITIVE_POLICY_DROP_FEATURES",
    "NOISE_NONPOSITIVE_POLICY_DROP_PATTERN",
    "NOISE_NONPOSITIVE_POLICY_FILTER_NONPOSITIVE_FEATURES",
    "NOISE_NONPOSITIVE_POLICY_STRICT",
    "NativeReferenceDistanceEngine",
    "NoiseNormalization",
    "PATTERN_ID_COLUMN",
    "PreparedMvpaDistanceProvenanceRow",
    "PreparedMvpaDistanceQcRow",
    "PreparedMvpaDistanceResult",
    "PreparedMvpaDistanceRow",
    "PreparedMvpaDistanceSummaryProvenanceRow",
    "PreparedMvpaDistanceSummaryQcRow",
    "PreparedMvpaDistanceSummaryResult",
    "PreparedMvpaPatternGroup",
    "PreparedMvpaPatternRow",
    "PatternDataset",
    "PatternObservation",
    "RDM_INDEX_COLUMN",
    "REQUIRED_PATTERN_COLUMNS",
    "SUPPORTED_MVPA_ROW_PREPARATION_CV_UNITS",
    "SUPPORTED_NOISE_NONPOSITIVE_POLICIES",
    "condition_order",
    "compute_manual_diagonal_crossnobis_v1",
    "compute_mvpa_distances_from_prepared_groups",
    "cv_units_by_condition",
    "distance_summary_rows_from_estimates",
    "distance_summary_rows_from_long_rows",
    "pattern_dataset_from_rows",
    "plan_or_execute_mvpa_table_export",
    "plan_or_execute_mvpa_figure_export",
    "plan_or_execute_mvpa_rdm_export",
    "plan_or_execute_mvpa_derivative_publish",
    "plan_or_execute_mvpa_publication_export",
    "prepared_mvpa_distance_summary_rows",
    "plan_prepared_mvpa_distance_outputs",
    "plan_prepared_mvpa_pattern_outputs",
    "plan_prepared_mvpa_summary_outputs",
    "prepare_mvpa_pattern_row_groups",
    "rdm_long_rows_from_estimates",
    "rdm_wide_rows_from_estimates",
    "summarize_prepared_mvpa_distances",
    "validate_cross_validation",
    "validate_mvpa_table_export_document",
    "validate_mvpa_figure_export_document",
    "validate_mvpa_rdm_export_document",
    "validate_mvpa_derivative_publish_document",
    "validate_mvpa_publication_export_document",
    "write_mvpa_runtime_json",
    "write_mvpa_runtime_tsv",
    "write_prepared_mvpa_distance_outputs",
    "write_prepared_mvpa_pattern_outputs",
    "write_prepared_mvpa_summary_outputs",
]
