"""FSL-oriented neuro helpers."""

from .common import build_bids_base, infer_nvols_and_tr, normalize_entity_label, parse_bidsish_entities
from .feat_design import (
    ConditionPeMapping,
    ConditionPeMappingResult,
    ContrastAliasCopeMapping,
    ContrastAliasCopeMappingResult,
    ContrastCopeMapping,
    ContrastCopeMappingResult,
    EvTitlePeMapping,
    EvTitlePeMappingResult,
    FslContrastName,
    FslContrastNameParseResult,
    FslDesignParseResult,
    FslEvTitle,
    map_contrast_names_to_cope_numbers,
    map_conditions_to_pe_numbers,
    map_ev_titles_to_pe_numbers,
    parse_fsl_design_contrast_file,
    parse_fsl_design_contrast_names,
    parse_fsl_design_ev_titles,
    parse_fsl_design_file,
    resolve_contrast_aliases_to_cope_numbers,
)
from .flame import (
    FixedEffectsDesignPaths,
    FixedEffectsCommandPlan,
    build_flame1_command_plan,
    build_fixed_effects_command_plan,
    execute_flame1_command_plan,
    fixed_effects_design_paths,
    write_fixed_effects_design,
    write_one_sample_group_mean_design,
)
from .featquery import build_featquery_command_plan, execute_featquery_command_plan, parse_featquery_report

__all__ = [
    "build_flame1_command_plan",
    "build_fixed_effects_command_plan",
    "build_featquery_command_plan",
    "build_bids_base",
    "ConditionPeMapping",
    "ConditionPeMappingResult",
    "ContrastAliasCopeMapping",
    "ContrastAliasCopeMappingResult",
    "ContrastCopeMapping",
    "ContrastCopeMappingResult",
    "EvTitlePeMapping",
    "EvTitlePeMappingResult",
    "execute_flame1_command_plan",
    "execute_featquery_command_plan",
    "fixed_effects_design_paths",
    "FixedEffectsCommandPlan",
    "FixedEffectsDesignPaths",
    "FslContrastName",
    "FslContrastNameParseResult",
    "FslDesignParseResult",
    "FslEvTitle",
    "infer_nvols_and_tr",
    "map_contrast_names_to_cope_numbers",
    "map_conditions_to_pe_numbers",
    "map_ev_titles_to_pe_numbers",
    "normalize_entity_label",
    "parse_fsl_design_contrast_file",
    "parse_fsl_design_contrast_names",
    "parse_fsl_design_ev_titles",
    "parse_fsl_design_file",
    "parse_featquery_report",
    "parse_bidsish_entities",
    "resolve_contrast_aliases_to_cope_numbers",
    "write_fixed_effects_design",
    "write_one_sample_group_mean_design",
]
