"""Research-io package."""

from .dataframe.adapters import supports_backend, supported_formats
from .dataframe.ops import (
    collect_tabular,
    concat_tabular,
    inspect_columns_with_nulls,
    inspect_describe,
    inspect_dtypes,
    inspect_nulls,
    merge_tabular,
    merge_tabulars,
    drop_rows_by_id_values,
    drop_rows_by_row_numbers,
    fill_missing_with_median,
    fill_missing_with_mode,
    preview_tabular,
    replace_invalid_values,
)
from .dataframe.records import (
    DATAFRAME_RECORDS_ADAPTER_VERSION,
    DataframeRecordsAdapter,
    DataframeRecordsAdapterSpec,
    DataframeRecordsProvenanceRow,
    DataframeRecordsQcRow,
    DataframeRecordsResult,
    dataframe_to_records,
    detect_dataframe_like_protocol,
    inspect_dataframe_like_source,
    iter_dataframe_records,
    plan_dataframe_records_adapter,
)
from .dataframe.association_records import (
    TABULAR_ASSOCIATION_SOURCE_ROWS_BACKENDS,
    TABULAR_ASSOCIATION_SOURCE_ROWS_RUNTIME_BACKEND,
    TABULAR_ASSOCIATION_SOURCE_ROWS_VERSION,
    TabularAssociationSourceRowsResult,
    prepare_tabular_association_source_rows,
)
from .dataframe.pandas_ops import (
    DEFAULT_PANDAS_INDEX_FIELD,
    PANDAS_RECORDS_ADAPTER_VERSION,
    PandasRecordsAdapter,
    detect_pandas_dataframe_protocol,
    inspect_pandas_dataframe_source,
    iter_pandas_dataframe_records,
    pandas_dataframe_to_records,
    plan_pandas_records_adapter,
)
from .dataframe.polars_ops import (
    POLARS_RECORDS_ADAPTER_KIND,
    POLARS_RECORDS_ADAPTER_VERSION,
    PolarsRecordsAdapter,
    detect_polars_dataframe_protocol,
    inspect_polars_dataframe_source,
    iter_polars_dataframe_records,
    plan_polars_records_adapter,
    polars_dataframe_to_records,
)
from .readers.tabular import read_tabular, read_tabulars
from .writers.tabular import write_tabular

__all__ = [
    "collect_tabular",
    "concat_tabular",
    "merge_tabular",
    "merge_tabulars",
    "preview_tabular",
    "inspect_dtypes",
    "inspect_describe",
    "inspect_nulls",
    "inspect_columns_with_nulls",
    "replace_invalid_values",
    "fill_missing_with_median",
    "fill_missing_with_mode",
    "drop_rows_by_row_numbers",
    "drop_rows_by_id_values",
    "DATAFRAME_RECORDS_ADAPTER_VERSION",
    "PANDAS_RECORDS_ADAPTER_VERSION",
    "POLARS_RECORDS_ADAPTER_KIND",
    "POLARS_RECORDS_ADAPTER_VERSION",
    "DEFAULT_PANDAS_INDEX_FIELD",
    "TABULAR_ASSOCIATION_SOURCE_ROWS_BACKENDS",
    "TABULAR_ASSOCIATION_SOURCE_ROWS_RUNTIME_BACKEND",
    "TABULAR_ASSOCIATION_SOURCE_ROWS_VERSION",
    "DataframeRecordsAdapter",
    "DataframeRecordsAdapterSpec",
    "DataframeRecordsProvenanceRow",
    "DataframeRecordsQcRow",
    "DataframeRecordsResult",
    "PandasRecordsAdapter",
    "PolarsRecordsAdapter",
    "TabularAssociationSourceRowsResult",
    "dataframe_to_records",
    "detect_dataframe_like_protocol",
    "detect_pandas_dataframe_protocol",
    "detect_polars_dataframe_protocol",
    "inspect_dataframe_like_source",
    "inspect_pandas_dataframe_source",
    "inspect_polars_dataframe_source",
    "iter_dataframe_records",
    "iter_pandas_dataframe_records",
    "iter_polars_dataframe_records",
    "pandas_dataframe_to_records",
    "polars_dataframe_to_records",
    "plan_dataframe_records_adapter",
    "plan_pandas_records_adapter",
    "plan_polars_records_adapter",
    "prepare_tabular_association_source_rows",
    "read_tabular",
    "read_tabulars",
    "write_tabular",
    "supports_backend",
    "supported_formats",
]
